### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by mohannadbahar** [MahdiSharara/Secured-Text-and-Voice-Chatting-Application-Using-JAVA#1]
Hello
How to run the program
Because in all cases it gives the wrong message  :- Server is down

**Comment by MahdiSharara** [comment]
Hello. To run the program, got to the Server folder and run "ServerGraphicalInterface". This will start the server. To run a client, go to Client Folder and run "LogInSignUpScreen" @mohannadbahar
